# Lumo partitioning defaults
efi:
    recommendedSize:    512MiB
    minimumSize:        100MiB
    label:              "EFI System"

partitionLabels:
    structured: true

initialPartitioningChoice: erase
initialSwapChoice: swap

drawNestedPartitions: false
alwaysShowPartitionLabels: true

defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs"]
