# Lumo users module
userShell: /bin/bash
setRootPassword: false
doReusePassword: false
doAutologin: false

sudoersGroup: sudo

defaultGroups:
    - cdrom
    - sudo
    - audio
    - video
    - netdev
    - input
    - users
    - lp

autologinGroup: autologin
avatarFilePath: ~/.face

hostname:
    location: EtcFile
    assignment: IfTool
    locked: false
