# Lumo welcome requirements
requirements:
    requiredStorage: 8
    requiredRam: 1.5
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram

geoip:
    style: "none"

welcomeStyle: true
welcomeExplogPos: 0
