# Lumo OS portal preferences: wlr portal for screenshots/screencast,
# GTK portal for file chooser and friends.
[preferred]
default=gtk;
org.freedesktop.impl.portal.ScreenCast=wlr;
org.freedesktop.impl.portal.Screenshot=wlr;
org.freedesktop.impl.portal.GlobalShortcuts=wlr;
org.freedesktop.impl.portal.FileChooser=gtk;
org.freedesktop.impl.portal.Wallpaper=gtk;
